apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-k8s-app
  namespace: devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-k8s-app
  template:
    metadata:
      labels:
        app: simple-k8s-app
    spec:
      containers:
        - name: simple-k8s-app
          image: madhan68/simple-k8s-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
