apiVersion: v1
kind: Service
metadata:
  name: simple-k8s-service
  namespace: devops-project
spec:
  selector:
    app: simple-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
